require("vim._core.ui2").enable({})

require("options")
require("keymaps")
require("colorschema")
require("commands")
require("pack")
require("plugins.telescope")
require("plugins.lualine")
require("plugins.mini")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.whichkey")
require("plugins.diagnostic")
require("plugins.code-actions")
require("plugins.neo-tree")
