set-option -g default-shell /bin/zsh

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Vim Tmux Navigator
set -g @plugin 'christoomey/vim-tmux-navigator'

# Catppuccin theme
set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_text " #I: #W "
set -g @catppuccin_window_current_text " #I: #W "

# Terminal type configuration
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# remap prefix to Control + space
unbind C-b
set -g prefix C-space
bind C-space send-prefix

# reload config file
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux.conf reloaded!"


# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# don't rename windows automatically
set-option -g allow-rename off

# set zsh as default shell
set -g default-command /bin/zsh
set -g default-shell /bin/zsh

# add mouse support
set-option -g mouse on

# Keep plenty of history for scrollback
set -g history-limit 10000

# resize panes using the arrow keys
# might as well use them for something
bind Right resize-pane -R 5
bind Left resize-pane -L 5
bind Up resize-pane -U 2
bind Down resize-pane -D 2

# floating terminal popup in current directory
bind t popup -d "#{pane_current_path}" -E -w 80% -h 80% "zsh"

# floating lazygit popup in current directory
bind g popup -d "#{pane_current_path}" -E -w 80% -h 80% "lazygit"

# floating ghui popup in current directory
bind G popup -d "#{pane_current_path}" -E -w 80% -h 80% "ghui"

######################
### DESIGN CHANGES ###
######################

# improve colors
set -g default-terminal "screen-256color"

# status bar
set -g status-interval 2
set -g status-right-length 59
set -g renumber-windows on
set-option -g base-index 1
set-window-option -g pane-base-index 1
set-option -g status-position bottom

# Fig Tmux Integration: Enabled
source-file ~/.fig/tmux
# End of Fig Tmux Integration

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
